site_name: "Drizzle: The Unveiling"

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true

nav:
  - Design:
    - Introduction: "gdd/intro.md"
    - Concept: "gdd/concept.md"
    - Story: "gdd/story.md"
    - Art: "gdd/art.md"
    - Audio: "gdd/audio.md"
    - Game Experience: "gdd/exp.md"
  - Wiki: "wiki_index.md"